# docker-compose.yml
networks:
  box-network:
    driver: bridge

services:
  box:
    container_name: boilerplate
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      LOG_FILE: false
      NODE_ENV: ${NODE_ENV}
      HTTP_PORT: ${HTTP_PORT}
      DATABASE_URL: ${DATABASE_URL}
      GRPC_PORT: ${GRPC_PORT}
      RABBITMQ_URL: ${RABBITMQ_URL}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE}
      DOCS_USER: ${DOCS_USER}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - 3000:3000
    volumes:
      - ./:/home/app/boilerplate-nestjs
      - ./node_modules:/home/app/boilerplate-nestjs/node_modules
    networks:
      - box-network
    restart: unless-stopped
